# Generated by Django 4.1 on 2022-08-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='performer',
            new_name='executor',
        ),
    ]
