# Generated by Django 4.1 on 2022-09-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasklabelsrelations_alter_task_labels_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasklabelsrelations',
            table='task_labels',
        ),
    ]
