# Generated by Django 4.1 on 2022-09-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasklabelsrelations_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasklabelsrelations',
            table=None,
        ),
    ]
