# Generated by Django 4.1 on 2022-09-22 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_tasklabelsrelations_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabelsrelations',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task'),
        ),
    ]
